services:
  inference:
    container_name: inference-basic-eth-pred
    build:
      context: .
    command: python -u /app/app.py
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/inference/ETH"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - ./inference-data:/app/data
  
  updater:
    container_name: updater-basic-eth-pred
    build: .
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8000
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 24h;
      done
      "
    depends_on:
      inference:
        condition: service_healthy

  worker:
    container_name: worker-basic-eth-pred
    environment:
      - ACCOUNT_NAME=worker-account
      - ACCOUNT_MNEMONIC=your-mnemonic
      - INFERENCE_API_ADDRESS=http://inference:8000
      - TOPIC_ID=1
      - BOOT_NODES_URL=https://raw.githubusercontent.com/allora-network/networks/main/allora-testnet-1/heads.txt
      - ALLORA_RPC=https://allora-rpc.testnet-1.testnet.allora.network/
    build:
      context: .
      dockerfile: Dockerfile_b7s
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        set -ex

        # Define my public IP for dialback address
        MY_IP=$(curl -4 icanhazip.com)
        
        # Echo run the worker
        allora-node \
        --role=worker \
        --peer-db=/data/peer-database \
        --function-db=/data/function-database \
        --runtime-path=/app/runtime \
        --runtime-cli=bls-runtime \
        --workspace=/data/workspace \
        --private-key=/data/keys/priv.bin \
        --boot-nodes=$(curl -Ls $${BOOT_NODES_URL}) \
        --allora-chain-home-dir=/data/.allorad \
        --allora-node-rpc-address=$${ALLORA_RPC} \
        --allora-chain-key-name=$${ACCOUNT_NAME} \
        --allora-chain-restore-mnemonic=$${ACCOUNT_MNEMONIC} \
        --allora-chain-topic-id=$${TOPIC_ID} \
        --topic=allora-topic-$${TOPIC_ID}-worker \
        --dialback-address=$${MY_IP} \
        --dialback-port=9010 \
        --port=9010 \
        --log-level=debug
    volumes:
      - ./worker-data:/data
    working_dir: /data
    ports:
      - "9010:9010" # expose p2p port (should match values of `--dialback-port`:`--port`)
      - "2112:2112" # expose metrics port
    depends_on:
      - inference

volumes:
  inference-data:
  worker-data:
  head-data:
